export const PARTICIPANT_STATUSES = {
  UNKNOWN: -1,
  INVITED: 0,
  ACTIVE: 1,
  BANNED: 2,
  REFUSED: 3,
  OWNER: 4,
  WAIT_APPROVAL: 5,
};

export const PARTICIPANT_STATUSES_NAMES = {
  [PARTICIPANT_STATUSES.UNKNOWN]: 'Unknown',
  [PARTICIPANT_STATUSES.INVITED]: 'Invited',
  [PARTICIPANT_STATUSES.ACTIVE]: 'Participating',
  [PARTICIPANT_STATUSES.BANNED]: 'Banned',
  [PARTICIPANT_STATUSES.REFUSED]: 'Refused invite',
  [PARTICIPANT_STATUSES.OWNER]: 'Owner',
  [PARTICIPANT_STATUSES.WAIT_APPROVAL]: 'Waiting approval',
}

export const allowedUserStatuses = [
  PARTICIPANT_STATUSES.OWNER,
  PARTICIPANT_STATUSES.ACTIVE,
]