@@ .. @@
 //@ts-check
-import { AnimatedComponent } from '../../../shared/ui/base'
-import { BudgetListWidget } from '../../../widgets/budget-list'
-import { BudgetDetailsWidget } from '../../../widgets/budget-details'
-import { Store } from '../../../shared/lib/store'
-import { Router } from '../../../shared/lib/router'
-import { importStyle } from '../../../shared/lib/imports'
-import { FeatureDetector } from '../../../shared/lib/feature-detector'
-import { NewBudgetWidget } from '../../../widgets/new-budget'
-import { AuthManager } from '../../../shared/lib/auth'
+import { AnimatedComponent } from '../../../shared/ui/base.mjs'
+import { BudgetListWidget } from '../../../widgets/budget-list/index.mjs'
+import { BudgetDetailsWidget } from '../../../widgets/budget-details/index.mjs'
+import { Store } from '../../../shared/lib/store.mjs'
+import { Router } from '../../../shared/lib/router.mjs'
+import { importStyle } from '../../../shared/lib/imports.mjs'
+import { FeatureDetector } from '../../../shared/lib/feature-detector.mjs'
+import { NewBudgetWidget } from '../../../widgets/new-budget/index.mjs'
+import { AuthManager } from '../../../shared/lib/auth.mjs'